title: Annie Streater
description: Portfolio and musings
plugins:
  - jekyll-relative-links # converts links to markdown files to their html counterparts
relative_links:
  enabled: true
  collections: true
include:
  - index.html
  - 20_about.html
  - 30_resume.html
  - /work/index.html
  - /case-studies/index.html
  - /craft-notes/index.html
  - 70_accessibility-statement.html
  - 80_contact.html
exclude:
  - 404.md
  - /case-studies/daye-closing-shop.md
  - /case-studies/discount-codes.md
  - /case-studies/multiply-conversational-design.md
  - /craft-notes/bug-prioritization-matrix.md
  - /craft-notes/making-resume-accessible.md
  - /craft-notes/technical-writer-cover-letter.md
  - /craft-notes/transferable-skills.md
  - /craft-notes/vogue-a11y-fail.md
  - /work/multiply-language-style.md
  - index.html
remote_theme: streats/streats.github.io
