title: Annie Streater
description: Portfolio and musings
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
collections: 
  menu-links:
    output: true
    sort-by: navigation_weight
include:
  - index.html
  - about.html
  - resume.html
  - /work/index.html
  - /case-studies/index.html
  - /craft-notes/index.html
  - accessibility-statement.html
  - contact.html
````
exclude:
    - 404.md
    - README.md
    - /case-studies/daye-closing-shop.md
    - /case-studies/discount-codes.md
    - /case-studies/multiply-conversational-design.md
    - /work/multiply-language-style.md
    - /craft-notes/making-resume-accessible.md
    - /craft-notes/transferable-skills.md
    - /craft-notes/bug-prioritization-matrix.md
    - /craft-notes/vogue-a11y-fail.md
    - /craft-notes/technical-writer-cover-letter.md
    - drums-for-sale.md
````
theme: minima
