title: Annie Streater
description: Portfolio and musings
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
collections: 
  menu-links:
    output: true
    sort-by: navigation_weight
include:
  - index.html
  - about.html
  - resume.html
  - /work/index.html
  - /case-studies/index.html
  - /craft-notes/index.html
  - accessibility-statement.html
  - contact.html
exclude:
    - drums-for-sale.md
theme: minima
