title: Annie Streater
description: Portfolio and musings
plugins:
  - jekyll-relative-links # converts links to markdown files to their html counterparts
relative_links:
  enabled: true
  collections: true
include:
  - index.html
  - about.html
  - resume.html
  - /work/index.html
  - /case-studies/index.html
  - /craft-notes/index.html
  - accessibility-statement.html
  - contact.html
exclude:
  - 404.md
theme: minima
