title: Annie Streater
description: Portfolio and musings
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
collections: 
  menu-links:
    sort-by: navigation_weight
include:
  - CONTRIBUTING.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
exclude:
    - 404.md
    - README.md
    - /case-studies/daye-closing-shop.md
    - /case-studies/discount-codes.md
    - /case-studies/multiply-conversational-design.md
    - /work/multiply-language-style.md
    - /craft-notes/making-resume-accessible.md
    - /craft-notes/transferable-skills.md
    - /craft-notes/bug-prioritization-matrix.md
    - /craft-notes/vogue-a11y-fail.md
    - /craft-notes/technical-writer-cover-letter.md
theme: minima