title: Annie Streater
description: Portfolio and musings
plugins:
  - jekyll-relative-links # converts links to markdown files to their html counterparts
relative_links:
  enabled: true
  collections: true
includes:
  - index.html
  - about.html
  - resume.html
  - /work/index.html
  - /case-studies/index.html
  - /craft-notes/index.html
  - accessibility-statement.html
  - contact.html
excludes: 
  - 404.md
  - /craft-notes/bug-prioritization-matrix.md
  - /craft-notes/transferable-skills.md
  - /craft-notes/technical-writer.md
  - /craft-notes/vogue-a11y-fail.md
  - /case-studies/discount-codes.md
  - /case-studies/closing-up-shop/md
  - /case-studies/multiply-conversational-design.md
  - /work/making-resume-accessible.md
  - /work/multiply-language-style.md
  
theme: minima

