#-------------------------------
# General Site Settings

menu:
- {name: 'Welcome', url: 'index'}
- {name: 'About',    url: 'about'}
- {name: 'Resume',    url: 'resume'}
- {name: 'Work', url: 'work'}
- {name: 'Case Studies',    url: 'case-studies'}
- {name: 'Craft Notes',    url: 'craft-notes'}
- {name: 'Contact',  url: 'contact'}

#-------------------------------
# Case Studies Section

case-studies:
- {name: 'Closing up shop',   url: 'closing-up-shop'}
- {name: 'Discount codes',   url: 'discount-codes'}
- {name: 'Conversational design', url: 'conversational-design'}

#-------------------------------
# Contact Section

social:
- {icon: 'github',    link: 'https://github.com/streats'}
- {icon: 'linkedin',  link: 'https://linkedin.com/in/streats'}
- {icon: 'envelope',  link: 'mailto:streat0r@icloud.com'}
